#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define XGBOOST_FEATURE_COUNT 38

typedef enum {
    XGB_FEATURE_D_ACT = 0,
    XGB_FEATURE_W_ACT = 1,
    XGB_FEATURE_P_ACT = 2,
    XGB_FEATURE_PERC_ACT = 3,
    XGB_FEATURE_IDP = 4,
    XGB_FEATURE_D = 5,
    XGB_FEATURE_W = 6,
    XGB_FEATURE_P = 7,
    XGB_FEATURE_PERCENT = 8,
    XGB_FEATURE_ANG = 9,
    XGB_FEATURE_DATE_TS = 10,
    XGB_FEATURE_SEN_ANG = 11,
    XGB_FEATURE_COS_ANG = 12,
    XGB_FEATURE_ANG_IS_CALCULATING = 13,
    XGB_FEATURE_WINDOW_LAG5_P_CHANGED_CENTERED_11 = 14,
    XGB_FEATURE_WINDOW_LAG5_W_CHANGED_CENTERED_11 = 15,
    XGB_FEATURE_WINDOW_LAG5_D_CHANGED_CENTERED_11 = 16,
    XGB_FEATURE_WINDOW_LAG5_IDP_30_COUNT_CENTERED_11 = 17,
    XGB_FEATURE_WINDOW_LAG5_TOTAL_TIME_DELTA_SEC_CENTERED_11 = 18,
    XGB_FEATURE_WINDOW_LAG5_HAS_ACTION_CENTERED_11 = 19,
    XGB_FEATURE_WINDOW_POS5_P_CHANGED_CENTERED_11 = 20,
    XGB_FEATURE_WINDOW_POS5_W_CHANGED_CENTERED_11 = 21,
    XGB_FEATURE_WINDOW_POS5_D_CHANGED_CENTERED_11 = 22,
    XGB_FEATURE_WINDOW_POS5_IDP_30_COUNT_CENTERED_11 = 23,
    XGB_FEATURE_WINDOW_POS5_TOTAL_TIME_DELTA_SEC_CENTERED_11 = 24,
    XGB_FEATURE_WINDOW_POS5_HAS_ACTION_CENTERED_11 = 25,
    XGB_FEATURE_WINDOW_LAG5_DELTA_PERCENT_CENTERED_11 = 26,
    XGB_FEATURE_WINDOW_LAG5_RANGE_PERCENT_CENTERED_11 = 27,
    XGB_FEATURE_WINDOW_LAG5_MAX_DELTA_PERCENT_CENTERED_11 = 28,
    XGB_FEATURE_WINDOW_LAG5_DELTA_ANG_CENTERED_11 = 29,
    XGB_FEATURE_WINDOW_LAG5_RANGE_ANG_CENTERED_11 = 30,
    XGB_FEATURE_WINDOW_LAG5_MAX_DELTA_ANG_CENTERED_11 = 31,
    XGB_FEATURE_WINDOW_POS5_DELTA_PERCENT_CENTERED_11 = 32,
    XGB_FEATURE_WINDOW_POS5_RANGE_PERCENT_CENTERED_11 = 33,
    XGB_FEATURE_WINDOW_POS5_MAX_DELTA_PERCENT_CENTERED_11 = 34,
    XGB_FEATURE_WINDOW_POS5_DELTA_ANG_CENTERED_11 = 35,
    XGB_FEATURE_WINDOW_POS5_RANGE_ANG_CENTERED_11 = 36,
    XGB_FEATURE_WINDOW_POS5_MAX_DELTA_ANG_CENTERED_11 = 37,
} xgboost_feature_index_t;

#ifdef __cplusplus
}
#endif
