/**
 * @file actuation_app.h
 * @brief Application layer for the new four-channel actuation product.
 */

#ifndef COMPONENTS_APPLICATIONS_INCLUDE_ACTUATION_APP_H_
#define COMPONENTS_APPLICATIONS_INCLUDE_ACTUATION_APP_H_

#include "esp_err.h"
#include "project_config.h"

/**
 * @brief Empty command payload used when no relay pulse should be issued.
 */
extern const actuation_actions actuation_actions_none;

/**
 * @brief Initializes the actuation application and GPIO driver.
 */
esp_err_t actuation_app_init(const app_callback callback);

/**
 * @brief Applies actuation configuration.
 */
esp_err_t actuation_app_set_config(actuation_config config);

/**
 * @brief Requests pump start or stop according to the provided command payload.
 *
 * Any ON command starts the sequenced pumping logic. Any OFF command requests
 * the safety stop routine.
 */
void actuation_app_set_actions(const actuation_actions actions, bool alert_change);

/**
 * @brief Returns the last command payload accepted by the application.
 */
void actuation_app_get_actions(actuation_actions *actions_out, size_t actions_size);

/**
 * @brief Reads the live ON/OFF status from the four status inputs.
 */
void actuation_app_get_status(actuation_status *status_out, size_t status_size);

/**
 * @brief Returns true when all live status inputs indicate OFF.
 */
bool actuation_app_is_all_off(void);

/**
 * @brief Returns the current pump state name.
 */
const char *actuation_app_get_state_name(void);

/**
 * @brief Returns the last channel that failed validation, or 0 when there is no recorded fault.
 */
uint8_t actuation_app_get_last_fault_channel(void);

/**
 * @brief Copies the last shutdown event generated by the actuation task.
 *
 * @return Runtime event sequence, or 0 when no shutdown event was recorded yet.
 */
uint32_t actuation_app_get_shutdown_info(actuation_shutdown_info *info_out, size_t info_size);

/**
 * @brief De-energizes every relay output without issuing ON/OFF commands.
 */
void actuation_app_shutdown(void);

#endif /* COMPONENTS_APPLICATIONS_INCLUDE_ACTUATION_APP_H_ */
