/**
 * @file rush_mode.h
 * @brief Rush Mode public API.
 * @author soil-dev
 * @date 15 de out. de 2023
 */

#ifndef MAIN_INCLUDE_RUSH_MODE_H_
#define MAIN_INCLUDE_RUSH_MODE_H_

#include "project_config.h"

/**
 * @brief Starts Rush Mode with the given configuration.
 * @param current_rush_mode Rush Mode configuration.
 */
void rush_mode_start(rush_mode_config current_rush_mode);

/**
 * @brief Stops Rush Mode.
 */
void rush_mode_stop(void);

/**
 * @brief Suspends Rush Mode for the current window and clears any persisted restore state.
 *
 * When called during an active configured window, the current window remains suspended
 * until its end even after a reboot. Outside the configured window, any stale runtime
 * state is simply cleared.
 *
 * @param notify_override True to emit the rush override notification.
 */
void rush_mode_suspend_current_window(bool notify_override);

/**
 * @brief Handles a higher-priority command that may override the current Rush Mode window.
 *
 * Any external command can take priority over the current Rush Mode window.
 * When `override_on_any_idp_01` is true, the current window restore is invalidated even
 * for OFF commands. The rush override notification is emitted only when the pivot was
 * previously off and the command changes it to on.
 *
 * @param new_actions Actions requested by the current command.
 * @param old_actions Actions applied before the current command.
 * @param ignore_override True when the command itself was generated by Rush Mode.
 * @param override_on_any_idp_01 True to give priority to any external IDP 01 command.
 */
void rush_mode_handle_override(const pivot_actions *new_actions, const pivot_actions *old_actions, bool ignore_override, bool override_on_any_idp_01);

/**
 * @brief Converts an HHMM value from IDP 04 into seconds since midnight.
 *
 * @param hhmm_value Time in HHMM format.
 * @param seconds_out Output buffer for the converted value in seconds.
 * @return true when the value is a valid HHMM time, false otherwise.
 */
bool rush_mode_hhmm_to_seconds(uint32_t hhmm_value, time_t *seconds_out);

/**
 * @brief Formats seconds since midnight into a zero-padded HHMM string.
 *
 * @param seconds_value Time value stored internally in seconds.
 * @param hhmm_out Output buffer for the HHMM string.
 * @param hhmm_out_size Output buffer size.
 */
void rush_mode_seconds_to_hhmm_string(time_t seconds_value, char *hhmm_out, size_t hhmm_out_size);

/**
 * @brief Registers a callback for Rush Mode events.
 * @param callback Callback to be registered.
 */
void rush_mode_register_callback(const app_callback callback);

#endif /* MAIN_INCLUDE_RUSH_MODE_H_ */
